// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tur29St2HMPtxLkcZZpSx4PC-LdHgm8',
    appId: '1:766377888172:web:1e4cc440304f0d222b1209',
    messagingSenderId: '766377888172',
    projectId: 'fir-blog-6b3ea',
    authDomain: 'fir-blog-6b3ea.firebaseapp.com',
    storageBucket: 'fir-blog-6b3ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmjgBHNoo-cFa85oFtxtj3-_W_k73YUk',
    appId: '1:766377888172:android:698e5b0133804f7f2b1209',
    messagingSenderId: '766377888172',
    projectId: 'fir-blog-6b3ea',
    storageBucket: 'fir-blog-6b3ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAxtbwFtYffpPzMJ3DJzdZCUUk28Xppuk',
    appId: '1:766377888172:ios:696da284899aa1af2b1209',
    messagingSenderId: '766377888172',
    projectId: 'fir-blog-6b3ea',
    storageBucket: 'fir-blog-6b3ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAxtbwFtYffpPzMJ3DJzdZCUUk28Xppuk',
    appId: '1:766377888172:ios:696da284899aa1af2b1209',
    messagingSenderId: '766377888172',
    projectId: 'fir-blog-6b3ea',
    storageBucket: 'fir-blog-6b3ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7tur29St2HMPtxLkcZZpSx4PC-LdHgm8',
    appId: '1:766377888172:web:f38dce3e627c5c742b1209',
    messagingSenderId: '766377888172',
    projectId: 'fir-blog-6b3ea',
    authDomain: 'fir-blog-6b3ea.firebaseapp.com',
    storageBucket: 'fir-blog-6b3ea.firebasestorage.app',
  );
}
